### ISSUE TITLE
react-dnd version upgrade

### ISSUE THREAD

**Issue by jamesdbrock** [lumihq/purescript-react-dnd-basic#6]
This library appears to be developed against [__react-dnd v2.6.0__ from 2018 March 22](https://github.com/react-dnd/react-dnd/releases?after=v4.0.2), and the latest version is __react-dnd v9.4.0__. It would be nice to upgrade to the latest version.

Thank you very much for publishing this library @spicydonuts . I'm not complaining. I'll try to submit a PR for this issue if I can manage it.

**Comment by spicydonuts** [comment]
A PR would be great. We're barely using this at the moment and it works for that case, so it's unlikely to get an update from us soon.

**Comment by jamesdbrock** [comment]
What do you use for drag-and-drop with React and Purescript @spicydonuts ?

**Comment by spicydonuts** [comment]
I haven't used it a lot, but for a few select cases just the html drag/drop api.

**Comment by jamesdbrock** [comment]
#12 :tada:
